inputs: assets/demo/layout_detection
outputs: outputs/layout_detection
tasks:
  layout_detection:
    model: layout_detection_yolo
    model_config:
      img_size: 1280
      conf_thres: 0.25
      iou_thres: 0.45
      batch_size: 2
      model_path: models/Layout/YOLO/yolov10l_ft.pt
      visualize: True
      rect: True
      device: "0"